version: 2
jobs:
  build:
    docker:
      - image: montanier/odette-kahn-dev:0.1.0
    steps:
      - checkout
      - run:
        name: "run tests"
        command: |
          export DB_PATH=/root/project/db
          export MODELS_PATH=/root/project/models
          pytest
